services:
  postgres:
    image: postgres:17-alpine
    container_name: sniplink-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: sniplink_short_db
    ports:
      - "5433:5432"
    volumes:
      - sniplink-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d sniplink_short_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres-analytics:
    image: postgres:17-alpine
    container_name: sniplink-postgres-analytics
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: sniplink_analytics_db
    ports:
      - "5434:5432"
    volumes:
      - sniplink-postgres-analytics-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d sniplink_analytics_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:4-management-alpine
    container_name: sniplink-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - sniplink-rabbitmq-data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  short-service:
    build: ./services/short-service
    container_name: sniplink-short-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/sniplink_short_db
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: "5672"
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
    ports:
      - "8082:8082"
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  analytics-service:
    build: ./services/analytics-service
    container_name: sniplink-analytics-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-analytics:5432/sniplink_analytics_db
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: "5672"
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
    ports:
      - "8083:8083"
    depends_on:
      postgres-analytics:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  frontend:
    build: ./frontend
    container_name: sniplink-frontend
    ports:
      - "4200:80"
    depends_on:
      - short-service
      - analytics-service

volumes:
  sniplink-postgres-data:
  sniplink-postgres-analytics-data:
  sniplink-rabbitmq-data:
